name: Terraform Apply 
run-name: ${{ github.actor }} is running a terraform plan 
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
  push:
    branches:
      - main
    types: [closed]

jobs:
  apply:
    name: terraform apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1
      - name: Terraform fmt
        run: terraform fmt  
      - name: Terraform apply
        run: terraform apply  
