name: Test Action
run-name: ${{ github.actor }} is testing gh actions
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
